### PR TITLE
fix #410 SimpleConsumer cannot seek to an absolute offset.

### LINKED ISSUE #410: SimpleConsumer cannot seek to an absolute offset.
Hello, currently kafka-python only provide a relative seek method. For example, when I call `consumer.seek(offset, 0)`. The offset for current consumer would became to current_oldest_offset + `offset`, not become to 0 + `offset`. How could I seek to a fix offset in kafka-python?

### PR DESCRIPTION
**Pull request by haosdent**

### CODE REVIEW

**Comment by haosdent** [comment]
ping @mumrah Please help me review this, thx.

**Comment by dpkp** [comment]
generally lgtm; can you take a stab at a test for this? test/test_consumer.py

**Comment by haosdent** [comment]
sure

**Comment by haosdent** [comment]
I add to `test/test_consumer_integration.py`

**Comment by dpkp** [comment]
thanks!

**Comment by haosdent** [comment]
Hi, @dpkp when would you merge this to release? I still could not see it in 0.9.4

**Pull request merged**
