### PR TITLE
Validate consumer offset in SimpleConsumer 

### PR DESCRIPTION
**Pull request by ecanzonieri**
I slightly changed the SimpleConsumer interface adding the default option use_latest_offsets. Resetting the offsets automatically is especially useful in MultiprocessConsumer, where an explicit call to the method seek is not possible. 

I manually tested it in my kafka cluster, but there are no integration tests for this feature, yet.
I think that tuning "log.retention.bytes" I should be able to implement two tests. 
Fix for #263

### CODE REVIEW

**Comment by jobevers** [comment]
:+1:

**Comment by ecanzonieri** [comment]
I changed the code to be more like KafkaConsumer. It now uses the keyword argument auto_offset_reset, which can be either "smallest" or "largest" (default), and falls back to the old behavior otherwise.

**Comment by farvour** [comment]
Can we get this merged in?

**Comment by dpkp** [comment]
LGTM

**Pull request merged**
